name: Deploy Lambda Function

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 
  pull-requests: write 
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_DEFALUT_REGION }}

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
          
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade

      # - name: Export variables from secret
      #   run: |
      #     ENV_JSON='${{ secrets.AWS_DEV_INFRA }}'
      #     echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFALUT_REGION }}
          role-session-name: GitHub-OIDC-LABDA-SESSION

      - name: Zip Lambda function
        run: |
          pwd
          cd ${GITHUB_WORKSPACE}/src
          zip -r function.zip amp_lambda_function/

      - name: Deploy Lambda function
        env:
          LAMBDA_LOG_GROUP_NAME: ${{ secrets.LAMBDA_LG }}
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNC }}
        run: |
          cd ${GITHUB_WORKSPACE}/src
          ls -la ${GITHUB_WORKSPACE}/src
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNC }} --zip-file fileb://function.zip --region ${{ secrets.AWS_DEFALUT_REGION }}
          sleep 25s
          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --tracing-config Mode=Active --environment Variables={LOG_GROUP_NAME=$LAMBDA_LOG_GROUP_NAME} --handler kamp_device_active_faults/lambda_function.lambda_handler
     
      # - name: Send logs to EC2 instance
      #   env:
      #     PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_PEM }}
      #     HOSTNAME: $EC2_1_IP
      #     USER_NAME: $KAMP_EC2_USER
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     aws logs filter-log-events \
      #       --log-group-name "$LAMBDA_LG" \
      #       --filter-pattern "" \
      #       --output text \
      #       --query 'events[*].message' | \
      #     ssh -o StrictHostKeyChecking=no -i private_key $KAMP_EC2_USER@$EC2_1_IP "mkdir -p ~/$GITHUB_JOB && cat >> ~/$GITHUB_JOB/aws_lambda_logs.txt"
      #     echo "Logs have been sent."  
