name: Deploy Lambda Function

on:
  push:
    branches:
      - main
#   workflow_dispatch:

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8

      - name: Export variables from secret
        run: |
          ENV_JSON='${{ secrets.AWS_DEV_INFRA }}'
          echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Print Secrets
        run: |
          echo "SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY"
          echo "ACCOUNT_ID: $ACCOUNT_ID"
          echo "AWS_REGION: $DEFAULT_REGION"
        

      # - name: Set up AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_DEV_INFRA.ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_DEV_INFRA.SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEV_INFRA.DEFAULT_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade

      - name: Zip Lambda function
        run: |
          zip -r function.zip ./src/amp_lambda_function/lambda_function.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ secrets.AWS_DEV_INFRA.LAMBDA_FUNC }} --zip-file fileb://function.zip
          sleep 15s
          aws lambda update-function-configuration --function-name ${{ secrets.AWS_DEV_INFRA.LAMBDA_FUNC }} --tracing-config Mode=Active --environment Variables={LOG_GROUP_NAME=${{ secrets.AWS_LAMBDA_LG }}} --handler src/amp_lambda_function/lambda_function.py

      - name: Set permissions for private key
        run: |
          chmod 600 ${{ secrets.PRIVATE_KEY_PEM }}
     
      - name: Send logs to EC2 instance
        run: |
          aws logs filter-log-events \
            --log-group-name "${{ secrets.AWS_DEV_INFRA.LAMBDA_LG }}" \
            --filter-pattern "" \
            --output text \
            --query 'events[*].message' | \
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY_PEM }} ${{ secrets.AWS_DEV_INFRA.EC2_USER }}@${{ secrets.AWS_DEV_INFRA.EC2_1_IP }} "mkdir -p ~/$GITHUB_JOB && cat >> ~/$GITHUB_JOB/aws_lambda_logs.txt"
          echo "Logs have been sent."  
